---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicloadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-lb
  template:
    metadata:
      labels:
        app: custom-lb
    spec:
      containers:
      - name: custom-lb
        image: andrewferruolo/basicloadbalancer:latest
        ports:
        - containerPort: 80
        
---
apiVersion: v1
kind: Service
metadata:
  name: basicloadbalancer-deployment
spec:
  type: NodePort  # or LoadBalancer, depending on your setup
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: basicloadbalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: andrewferruolo/server-node-container:latest
        ports:
        - containerPort: 8080

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: worker-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker-deployment
  minReplicas: 3
  maxReplicas: 10

